### ISSUE TITLE
Why is ‘include <codecvt>’ required for odbc 1.2.3 or 1.3.0?

### ISSUE THREAD

**Issue by EarlGlynn** [r-dbi/odbc#409]
### Issue Description and Expected Result

Could you release versions of `odbc` not dependent on `<codecvt>`?

I haven’t been able to use our RStudio Pro Servers for months for work with an Azure MS SQL database because odbc 1.2.3 (and now odbc 1.3.0) will not compile on our servers -- and odbc 1.2.2 had no problems compiling but has execution problems.

The new versions of `odbc` won’t compile because of a new requirement for `include <codecvt>`:

### Reproducible Example

```
devtools::install_version("odbc", version = "1.2.3", repos = "https://cran.rstudio.com/")
```

and

```
devtools::install_version("odbc", version = "1.3.0", repos = "https://cran.rstudio.com/")
```

have exactly the same compilation issue that was not present compiling odbc 1.2.2.:

```
nanodbc/nanodbc.cpp:40:19: fatal error: codecvt: No such file or directory
 #include <codecvt>
                   ^
compilation terminated.
make: *** [nanodbc.o] Error 1
ERROR: compilation failed for package ‘odbc’
```

We’re using CentOS 7, which supposedly has an end-of-life on July 7, 2024.  https://endoflife.software/operating-systems/linux/centos

Admittedly, our gcc compiler is a bit old but does compile odbc 1.2.2 successfully:

```
gcc –version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16)
```

Our admins tell me:  “Upgrading gcc will impact the compilation of all software on the server and so I do not know if we want to upgrade at this time.  ”

Why can’t RStudio support CentOS 7 for its full lifetime?

### Details

Newer odbc versions fixed bugs and added new features that I cannot now use on our RStudio Pro Server yet.   

Why must I use my PC and local RStudio Workstation to access a database that does not work from our RStudio Servers? 

This simple example works fine on a PC with newer versions of odbc, either 1.2.3 or 1.3.0, but not on our servers with odbc 1.2.2:

```{r}
HealthFacts <- 
  dbConnect(odbc(),
            Driver   = "ODBC Driver 17 for SQL Server",
            Server   = SERVER,
            Database = DATABASE,
            UID      = Sys.getenv("HF_UID"),  # from .Renviron file
            PWD      = Sys.getenv("HF_PWD"),
            Encrypt  = ifelse(Sys.info()["sysname"] == "Linux",
                             "yes",
                             "no"),
            TrustServerCertificate = "no",
            Connection_Timeout     = 30,
            bigint   = "integer")
```

```{r}
# Create small temporary table

tempName <- paste0("efg_temp_", format(Sys.time(), "%Y%m%d_%H%M%S"))
tempData <- tibble(a = c("A", "B", "C"),
                   i = 1:3)
tempTable <- copy_to(HealthFacts, tempData, tempName, temporary = TRUE)
```

```
Error in result_insert_dataframe(rs@ptr, values, batch_rows) : nanodbc/nanodbc.cpp:1617: 00000: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid object name '#efg_temp_20201203_124813'. [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Statement(s) could not be prepared.
16.
stop(structure(list(message = "nanodbc/nanodbc.cpp:1617: 00000: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid object name '#efg_temp_20201203_124813'. [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Statement(s) could not be prepared. ", call = result_insert_dataframe(rs@ptr, values, batch_rows), cppstack = NULL), class = c("nanodbc::database_error", "C++Error", "error", "condition")))
15.
result_insert_dataframe(rs@ptr, values, batch_rows)
14.
tryCatchList(expr, classes, parentenv, handlers)
13.
tryCatch(result_insert_dataframe(rs@ptr, values, batch_rows), finally = dbClearResult(rs))
12.
.local(conn, name, value, ...)
11.
dbWriteTable(con, name = dbi_quote(table, con), value = values, field.types = types, temporary = temporary, overwrite = overwrite, row.names = FALSE)
10.
dbWriteTable(con, name = dbi_quote(table, con), value = values, field.types = types, temporary = temporary, overwrite = overwrite, row.names = FALSE)
9.
db_write_table.DBIConnection(con, table, types = types, values = values, temporary = temporary, overwrite = overwrite)
8.
dplyr::db_write_table(con, table, types = types, values = values, temporary = temporary, overwrite = overwrite)
7.
with_transaction(con, in_transaction, { table <- dplyr::db_write_table(con, table, types = types, values = values, temporary = temporary, overwrite = overwrite) create_indexes(con, table, unique_indexes, unique = TRUE) ...
6.
db_copy_to.DBIConnection(dest$con, name, df, overwrite = overwrite, types = types, temporary = temporary, unique_indexes = unique_indexes, indexes = indexes, analyze = analyze, in_transaction = in_transaction, ...)
5.
db_copy_to(dest$con, name, df, overwrite = overwrite, types = types, temporary = temporary, unique_indexes = unique_indexes, indexes = indexes, analyze = analyze, in_transaction = in_transaction, ...)
4.
copy_to.src_sql(dbplyr::src_dbi(dest, auto_disconnect = FALSE), df = df, name = name, overwrite = overwrite, ...)
3.
copy_to(dbplyr::src_dbi(dest, auto_disconnect = FALSE), df = df, name = name, overwrite = overwrite, ...)
2.
copy_to.DBIConnection(HealthFacts, tempData, tempName, temporary = TRUE)
1.
copy_to(HealthFacts, tempData, tempName, temporary = TRUE)
```

**Comment by shrektan** [comment]
I think one workaround is to compile odbc on another CentOS machine and copy the binaries to your server...

**Comment by EarlGlynn** [comment]
Shannon Hagerty from RStudio Support gave me some very useful feedback:

Start here:
https://packagemanager.rstudio.com/client/#/repos/1/overview

Select "Latest" and "Binary" to see the latest binary packages for CentOS/RHEL 7.  

![image](https://user-images.githubusercontent.com/799010/101662225-dad0c400-3a0e-11eb-969c-cf189e9058fc.png)

This installed a local copy:

```
packageManager <- "https://packagemanager.rstudio.com/all/__linux__/centos7/latest"
devtools::install_version("odbc", version = "1.3.0", repos = packageManager)                         
```

The example above that had been failing now works fine!  No compiler needed.

**Comment by vishalsharma3003** [comment]
Try Lowering down the version of BH package to 1.78.0-0:

`devtools::install_version("BH", "1.78.0-0")`
